# Codespaces Prebuild Configuration
# This ensures Codespaces start quickly with dependencies pre-installed

name: Codespaces Prebuild

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  createPrebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Verify scripts
        run: |
          chmod +x *.sh
          echo "✅ Scripts ready"
